#!/bin/bash

set `lsusb -d ${ID_VENDOR}:${ID_MODEL}| sed 's/:.*//g'`
while [ ! -z "$1" ]; do
  case $1 in
    Bus) shift
    busdevice="$1"
    ;;
    Device) shift
    busdevice=${busdevice}"/$1"
    ;;
  esac
  shift
done
if [ ! -z "$busdevice" ]; then
  address=$(VBoxManage list usbhost | grep "Address:" | grep $bus device | sed -e 's/Address://' -e 's/^[ \t]*//')
  if [ ! -z "$address" ]; then
    while [  $NumberOfVMs -gt 0 ];do
       NumberOfVMs=replaceme
       su - guestos -c "VBoxManage controlvm guestos_$(printf %04g $NumberOfVMs) usbattach `VBoxManage list usbhost | grep "Address:" | grep $bus device | sed -e 's/Address://' -e 's/^[ \t]*//'`"
    let NumberOfVMs=NumberOfVMs-1
    done
  fi
fi
