#!/bin/bash

cp -r ../* ../../VubuntuBox_Files

cd ../..
mkisofs -r -V "VubuntuBox CD $1" -cache-inodes -J -l -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table -o "Disk_Images/VubuntuBox-$1.iso" "VubuntuBox_Files/"
cd VubuntuBox_Modifications/tools
