#!/bin/bash

cp -r ../* ../../DescartesDaemon_Files

cd ../..
mkisofs -r -V "Descartes Daemon $1" -cache-inodes -J -l -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table -o "Disk_Images/DescartesDaemon-$1.iso" "DescartesDaemon_Files/"
cd DescartesDaemon_Modifications/tools
